(function (global) {
  "use strict";

  const library = {
  "schemaVersion": "1.0.0",
  "libraryCode": "AS",
  "materialFamily": "ALLOY_STEEL",
  "modelName": "Alloy Steel Piping Service Cost Rate Library",
  "currency": "INR",
  "sourceDocument": "Chapter_2_ALLOY STEEL PIPING (NON IBR & IBR)(1).docx",
  "targetRepository": "https://github.com/medinikb/Piping-Cost-Estimator",
  "supportedLocations": [
    "ABOVE_GROUND"
  ],
  "supportedRegulatoryClasses": [
    "NON_IBR",
    "IBR"
  ],
  "measurementBasis": {
    "ID": "inch-diameter = weld or service joint count multiplied by applicable nominal diameter in inches",
    "IM": "inch-metre = nominal pipe size in inches multiplied by installed pipe length in metres",
    "M": "metre",
    "MAN_DAY": "8-hour man-day as stated in the source"
  },
  "governance": {
    "rateNature": "Source schedule-of-rates values, not market quotations.",
    "rateEscalation": "Apply a separately approved escalation factor. The library does not silently escalate source rates.",
    "riskAllowance": "Apply contingency separately from the direct service cost.",
    "unsupportedCombinations": "Return Review Required. Do not extrapolate outside documented size, thickness, IBR, or location ranges.",
    "doubleCountingGuardrail": "The broad piping scope already includes many fittings, testing and inline activities. Do not add duplicate costs without checking the source scope.",
    "materialSpecificGuardrail": "This chapter contains above-ground alloy-steel rates. Underground cases must return Review Required."
  },
  "rateTable": [
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 1470,
      "source": "NREP_4300080842 / 17.11.2023",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "FILLET_WELD",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 1176,
      "source": "Derived in uploaded document",
      "formulaReference": "=1470*80%",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 24,
      "unit": "IM",
      "rateRs": 310,
      "source": "BPCL-Kochi (=CS)",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 26,
      "npsMaxIn": 36,
      "unit": "IM",
      "rateRs": 320,
      "source": "BPCL-Kochi (=CS)",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 10,
      "thicknessMaxInclusiveMm": 20,
      "npsMinIn": 2,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 2559,
      "source": "Derived in uploaded document",
      "formulaReference": "=1470*(20/10)^0.8",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 10,
      "thicknessMaxInclusiveMm": 20,
      "npsMinIn": 2,
      "npsMaxIn": 36,
      "unit": "IM",
      "rateRs": 400,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 20,
      "thicknessMaxInclusiveMm": 30,
      "npsMinIn": 8,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 3540,
      "source": "Derived in uploaded document",
      "formulaReference": "=1470*(30/10)^0.8",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 20,
      "thicknessMaxInclusiveMm": 30,
      "npsMinIn": 8,
      "npsMaxIn": 24,
      "unit": "IM",
      "rateRs": 599,
      "source": "Derived in uploaded document",
      "formulaReference": "=310*(30/10)^0.6",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 20,
      "thicknessMaxInclusiveMm": 30,
      "npsMinIn": 26,
      "npsMaxIn": 36,
      "unit": "IM",
      "rateRs": 618,
      "source": "Derived in uploaded document",
      "formulaReference": "=320*(30/10)^0.6",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 30,
      "thicknessMaxInclusiveMm": 40,
      "npsMinIn": 8,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 4456,
      "source": "Derived in uploaded document",
      "formulaReference": "=1470*(40/10)^0.8",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 30,
      "thicknessMaxInclusiveMm": 40,
      "npsMinIn": 8,
      "npsMaxIn": 24,
      "unit": "IM",
      "rateRs": 712,
      "source": "Derived in uploaded document",
      "formulaReference": "=310*(40/10)^0.6",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 30,
      "thicknessMaxInclusiveMm": 40,
      "npsMinIn": 26,
      "npsMaxIn": 36,
      "unit": "IM",
      "rateRs": 735,
      "source": "Derived in uploaded document",
      "formulaReference": "=320*(40/10)^0.6",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 40,
      "thicknessMaxInclusiveMm": 50,
      "npsMinIn": 8,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 5327,
      "source": "Derived in uploaded document",
      "formulaReference": "=1470*(50/10)^0.8",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 40,
      "thicknessMaxInclusiveMm": 50,
      "npsMinIn": 8,
      "npsMaxIn": 24,
      "unit": "IM",
      "rateRs": 814,
      "source": "Derived in uploaded document",
      "formulaReference": "=310*(50/10)^0.6",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 40,
      "thicknessMaxInclusiveMm": 50,
      "npsMinIn": 26,
      "npsMaxIn": 36,
      "unit": "IM",
      "rateRs": 840,
      "source": "Derived in uploaded document",
      "formulaReference": "=320*(50/10)^0.6",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 1238,
      "source": "NREP_4300083969 / 18.04.2024",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "FABRICATION",
      "weldType": "FILLET_WELD",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 990,
      "source": "Derived in uploaded document",
      "formulaReference": "=1238*80%",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 24,
      "unit": "IM",
      "rateRs": 310,
      "source": "BPCL-Kochi (=CS)",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 26,
      "npsMaxIn": 36,
      "unit": "IM",
      "rateRs": 320,
      "source": "BPCL-Kochi (=CS)",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 10,
      "thicknessMaxInclusiveMm": 20,
      "npsMinIn": 4,
      "npsMaxIn": 24,
      "unit": "ID",
      "rateRs": 2155,
      "source": "Derived in uploaded document",
      "formulaReference": "=1238*(20/10)^0.8",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 10,
      "thicknessMaxInclusiveMm": 20,
      "npsMinIn": 4,
      "npsMaxIn": 24,
      "unit": "IM",
      "rateRs": 320,
      "source": "BPCL-Kochi (=CS)",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 20,
      "thicknessMaxInclusiveMm": 30,
      "npsMinIn": 8,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 2981,
      "source": "Derived in uploaded document",
      "formulaReference": "=1238*(30/10)^0.8",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 20,
      "thicknessMaxInclusiveMm": 30,
      "npsMinIn": 8,
      "npsMaxIn": 36,
      "unit": "IM",
      "rateRs": 490,
      "source": "BPCL-Kochi (=SS)",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 30,
      "thicknessMaxInclusiveMm": 40,
      "npsMinIn": 8,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 3752,
      "source": "Derived in uploaded document",
      "formulaReference": "=1238*(40/10)^0.8",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 30,
      "thicknessMaxInclusiveMm": 40,
      "npsMinIn": 8,
      "npsMaxIn": 36,
      "unit": "IM",
      "rateRs": 550,
      "source": "BPCL-Kochi (=SS)",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 40,
      "thicknessMaxInclusiveMm": 50,
      "npsMinIn": 8,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 4486,
      "source": "Derived in uploaded document",
      "formulaReference": "=1238*(50/10)^0.8",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 40,
      "thicknessMaxInclusiveMm": 50,
      "npsMinIn": 8,
      "npsMaxIn": 36,
      "unit": "IM",
      "rateRs": 681,
      "source": "Derived in uploaded document",
      "formulaReference": "=550*(50/35)^0.6",
      "note": ""
    },
    {
      "location": "ANY",
      "regulatoryClass": "NON_IBR",
      "activity": "FLAME_CUTTING",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 255,
      "source": "NRL-ME-AMC",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ANY",
      "regulatoryClass": "NON_IBR",
      "activity": "FLAME_CUTTING",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 10,
      "thicknessMaxInclusiveMm": 20,
      "npsMinIn": 0.5,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 386,
      "source": "Derived in uploaded document",
      "formulaReference": "=255*(20/10)^0.6",
      "note": ""
    },
    {
      "location": "ANY",
      "regulatoryClass": "NON_IBR",
      "activity": "FLAME_CUTTING",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 20,
      "thicknessMaxInclusiveMm": 30,
      "npsMinIn": 0.5,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 492,
      "source": "Derived in uploaded document",
      "formulaReference": "=255*(30/10)^0.6",
      "note": ""
    },
    {
      "location": "ANY",
      "regulatoryClass": "NON_IBR",
      "activity": "FLAME_CUTTING",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 30,
      "thicknessMaxInclusiveMm": 40,
      "npsMinIn": 0.5,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 585,
      "source": "Derived in uploaded document",
      "formulaReference": "=255*(40/10)^0.6",
      "note": ""
    },
    {
      "location": "ANY",
      "regulatoryClass": "NON_IBR",
      "activity": "FLAME_CUTTING",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 40,
      "thicknessMaxInclusiveMm": 50,
      "npsMinIn": 0.5,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 669,
      "source": "Derived in uploaded document",
      "formulaReference": "=255*(50/10)^0.6",
      "note": ""
    }
  ],
  "specialRates": {
    "salvaging": {
      "unit": "ID",
      "rateRs": 1211,
      "source": "IOC-ME-SOR (average)",
      "heightRule": "Beyond 5 m above or below ground, add 10% for each additional 5 m band.",
      "scaffolding": "Excluded and payable separately when required.",
      "applicability": "Schedule limits stated in the uploaded chapter must be checked before use."
    },
    "manpower": [
      {
        "category": "SKILLED",
        "unit": "MAN_DAY",
        "rateRs": 1760,
        "source": "BPCL-Kochi"
      },
      {
        "category": "SEMI_SKILLED",
        "unit": "MAN_DAY",
        "rateRs": 1700,
        "source": "BPCL-Kochi"
      },
      {
        "category": "UNSKILLED",
        "unit": "MAN_DAY",
        "rateRs": 1640,
        "source": "BPCL-Kochi"
      }
    ]
  }
};

  global.PIPING_SERVICE_COST_RATES_AS = library;
  global.PIPING_SERVICE_COST_RATE_LIBRARIES =
    global.PIPING_SERVICE_COST_RATE_LIBRARIES || {};
  global.PIPING_SERVICE_COST_RATE_LIBRARIES.AS = library;
})(typeof window !== "undefined" ? window : globalThis);
