window.PIPING_SERVICE_COST_RATES = {
  "schemaVersion": "1.0.0",
  "modelName": "Carbon Steel Piping Service Cost Rate Library",
  "currency": "INR",
  "sourceDocument": "48cbb0d7-738c-40dd-a0b8-0d4b1576b850.docx",
  "targetRepository": "https://github.com/medinikb/Piping-Cost-Estimator",
  "measurementBasis": {
    "ID": "inch-diameter = weld or service joint count multiplied by applicable nominal diameter in inches",
    "IM": "inch-metre = nominal pipe size in inches multiplied by installed pipe length in metres",
    "M": "metre",
    "MAN_DAY": "8-hour man-day as stated in the source"
  },
  "governance": {
    "rateNature": "Source schedule-of-rates values, not market quotations.",
    "rateEscalation": "Apply a separately approved escalation factor. The library does not silently escalate source rates.",
    "riskAllowance": "Apply contingency separately from the direct service cost.",
    "unsupportedCombinations": "Return Review Required. Do not extrapolate outside documented size, thickness, IBR, or location ranges.",
    "doubleCountingGuardrail": "The broad piping scope already includes many fittings, testing and inline activities. Do not add duplicate costs without checking the source scope."
  },
  "rateTable": [
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 48,
      "unit": "ID",
      "rateRs": 860,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "FILLET_WELD",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 48,
      "unit": "ID",
      "rateRs": 720,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 24,
      "unit": "IM",
      "rateRs": 310,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 26,
      "npsMaxIn": 48,
      "unit": "IM",
      "rateRs": 320,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 10,
      "thicknessMaxInclusiveMm": 20,
      "npsMinIn": 2,
      "npsMaxIn": 48,
      "unit": "ID",
      "rateRs": 1010,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 10,
      "thicknessMaxInclusiveMm": 20,
      "npsMinIn": 2,
      "npsMaxIn": 24,
      "unit": "IM",
      "rateRs": 320,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 10,
      "thicknessMaxInclusiveMm": 20,
      "npsMinIn": 26,
      "npsMaxIn": 48,
      "unit": "IM",
      "rateRs": 350,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 20,
      "thicknessMaxInclusiveMm": 30,
      "npsMinIn": 8,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 2071,
      "source": "Derived in uploaded document",
      "formulaReference": "=860*(30/10)^0.8",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 20,
      "thicknessMaxInclusiveMm": 30,
      "npsMinIn": 8,
      "npsMaxIn": 24,
      "unit": "IM",
      "rateRs": 599,
      "source": "Derived in uploaded document",
      "formulaReference": "=310*(30/10)^0.6",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 20,
      "thicknessMaxInclusiveMm": 30,
      "npsMinIn": 26,
      "npsMaxIn": 36,
      "unit": "IM",
      "rateRs": 618,
      "source": "Derived in uploaded document",
      "formulaReference": "=320*(30/10)^0.6",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 30,
      "thicknessMaxInclusiveMm": 40,
      "npsMinIn": 8,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 2607,
      "source": "Derived in uploaded document",
      "formulaReference": "=860*(40/10)^0.8",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 30,
      "thicknessMaxInclusiveMm": 40,
      "npsMinIn": 8,
      "npsMaxIn": 24,
      "unit": "IM",
      "rateRs": 712,
      "source": "Derived in uploaded document",
      "formulaReference": "=310*(40/10)^0.6",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 30,
      "thicknessMaxInclusiveMm": 40,
      "npsMinIn": 26,
      "npsMaxIn": 36,
      "unit": "IM",
      "rateRs": 735,
      "source": "Derived in uploaded document",
      "formulaReference": "=320*(40/10)^0.6",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 40,
      "thicknessMaxInclusiveMm": 50,
      "npsMinIn": 8,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 3116,
      "source": "Derived in uploaded document",
      "formulaReference": "=860*(50/10)^0.8",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 40,
      "thicknessMaxInclusiveMm": 50,
      "npsMinIn": 8,
      "npsMaxIn": 24,
      "unit": "IM",
      "rateRs": 814,
      "source": "Derived in uploaded document",
      "formulaReference": "=310*(50/10)^0.6",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 40,
      "thicknessMaxInclusiveMm": 50,
      "npsMinIn": 26,
      "npsMaxIn": 36,
      "unit": "IM",
      "rateRs": 840,
      "source": "Derived in uploaded document",
      "formulaReference": "=320*(50/10)^0.6",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 930,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "FABRICATION",
      "weldType": "FILLET_WELD",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 36,
      "unit": "ID",
      "rateRs": 820,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 24,
      "unit": "IM",
      "rateRs": 310,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 26,
      "npsMaxIn": 36,
      "unit": "IM",
      "rateRs": 320,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 10,
      "thicknessMaxInclusiveMm": 20,
      "npsMinIn": 4,
      "npsMaxIn": 24,
      "unit": "ID",
      "rateRs": 1090,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ABOVE_GROUND",
      "regulatoryClass": "IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 10,
      "thicknessMaxInclusiveMm": 20,
      "npsMinIn": 4,
      "npsMaxIn": 24,
      "unit": "IM",
      "rateRs": 320,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "UNDERGROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 48,
      "unit": "ID",
      "rateRs": 800,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "UNDERGROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 48,
      "unit": "IM",
      "rateRs": 430,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": "Includes corrosion protection coating and underground scope described in the source."
    },
    {
      "location": "UNDERGROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "FABRICATION",
      "weldType": "BUTT_WELD",
      "thicknessMinExclusiveMm": 10,
      "thicknessMaxInclusiveMm": 20,
      "npsMinIn": 2,
      "npsMaxIn": 48,
      "unit": "ID",
      "rateRs": 930,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "UNDERGROUND",
      "regulatoryClass": "NON_IBR",
      "activity": "ERECTION",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 10,
      "thicknessMaxInclusiveMm": 20,
      "npsMinIn": 2,
      "npsMaxIn": 48,
      "unit": "IM",
      "rateRs": 480,
      "source": "BPCL-Kochi",
      "formulaReference": "",
      "note": "Includes corrosion protection coating and underground scope described in the source."
    },
    {
      "location": "ANY",
      "regulatoryClass": "NON_IBR",
      "activity": "FLAME_CUTTING",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 0,
      "thicknessMaxInclusiveMm": 10,
      "npsMinIn": 0.5,
      "npsMaxIn": 48,
      "unit": "ID",
      "rateRs": 255,
      "source": "NRL-ME-AMC / derived in uploaded document",
      "formulaReference": "",
      "note": ""
    },
    {
      "location": "ANY",
      "regulatoryClass": "NON_IBR",
      "activity": "FLAME_CUTTING",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 10,
      "thicknessMaxInclusiveMm": 20,
      "npsMinIn": 0.5,
      "npsMaxIn": 48,
      "unit": "ID",
      "rateRs": 386,
      "source": "NRL-ME-AMC / derived in uploaded document",
      "formulaReference": "=255*(20/10)^0.6",
      "note": ""
    },
    {
      "location": "ANY",
      "regulatoryClass": "NON_IBR",
      "activity": "FLAME_CUTTING",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 20,
      "thicknessMaxInclusiveMm": 30,
      "npsMinIn": 0.5,
      "npsMaxIn": 48,
      "unit": "ID",
      "rateRs": 492,
      "source": "NRL-ME-AMC / derived in uploaded document",
      "formulaReference": "=255*(30/10)^0.6",
      "note": ""
    },
    {
      "location": "ANY",
      "regulatoryClass": "NON_IBR",
      "activity": "FLAME_CUTTING",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 30,
      "thicknessMaxInclusiveMm": 40,
      "npsMinIn": 0.5,
      "npsMaxIn": 48,
      "unit": "ID",
      "rateRs": 585,
      "source": "NRL-ME-AMC / derived in uploaded document",
      "formulaReference": "=255*(40/10)^0.6",
      "note": ""
    },
    {
      "location": "ANY",
      "regulatoryClass": "NON_IBR",
      "activity": "FLAME_CUTTING",
      "weldType": "NA",
      "thicknessMinExclusiveMm": 40,
      "thicknessMaxInclusiveMm": 50,
      "npsMinIn": 0.5,
      "npsMaxIn": 48,
      "unit": "ID",
      "rateRs": 669,
      "source": "NRL-ME-AMC / derived in uploaded document",
      "formulaReference": "=255*(50/10)^0.6",
      "note": ""
    }
  ],
  "specialRates": {
    "salvaging": {
      "unit": "ID",
      "rateRs": 390,
      "source": "IOC-ME-SOR",
      "heightRule": "Beyond 5 m above or below ground, add 10% for each additional 5 m band.",
      "scaffolding": "Excluded and payable separately when required.",
      "applicability": "Schedule limits stated in the uploaded document must be checked."
    },
    "steamTracer": {
      "supportedNpsIn": [
        0.5,
        0.75
      ],
      "unit": "M",
      "rateRs": 1010,
      "source": "BPCL-Kochi"
    },
    "manpower": [
      {
        "category": "SKILLED",
        "unit": "MAN_DAY",
        "rateRs": 1760,
        "source": "BPCL-Kochi"
      },
      {
        "category": "SEMI_SKILLED",
        "unit": "MAN_DAY",
        "rateRs": 1700,
        "source": "BPCL-Kochi"
      },
      {
        "category": "UNSKILLED",
        "unit": "MAN_DAY",
        "rateRs": 1640,
        "source": "BPCL-Kochi"
      }
    ]
  }
};
